package pojo;
// Generated Jun 7, 2014 10:51:16 PM by Hibernate Tools 3.6.0



/**
 * UserCompetion generated by hbm2java
 */
public class UserCompetion  implements java.io.Serializable {


     private Integer iduserCompetion;
     private User user;
     private Competition competition;
     private String solveTime;
     private Integer compScore;

    public UserCompetion() {
    }

    public UserCompetion(User user, Competition competition, String solveTime, Integer compScore) {
       this.user = user;
       this.competition = competition;
       this.solveTime = solveTime;
       this.compScore = compScore;
    }
   
    public Integer getIduserCompetion() {
        return this.iduserCompetion;
    }
    
    public void setIduserCompetion(Integer iduserCompetion) {
        this.iduserCompetion = iduserCompetion;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Competition getCompetition() {
        return this.competition;
    }
    
    public void setCompetition(Competition competition) {
        this.competition = competition;
    }
    public String getSolveTime() {
        return this.solveTime;
    }
    
    public void setSolveTime(String solveTime) {
        this.solveTime = solveTime;
    }
    public Integer getCompScore() {
        return this.compScore;
    }
    
    public void setCompScore(Integer compScore) {
        this.compScore = compScore;
    }




}


