package pojo;
// Generated May 3, 2014 1:08:24 PM by Hibernate Tools 3.2.1.GA



/**
 * UserCompetion generated by hbm2java
 */
public class UserCompetion  implements java.io.Serializable {


     private Integer iduserCompetion;
     private Competition competition;
     private User user;
     private String solveTime;
     private String compScore;

    public UserCompetion() {
    }

    public UserCompetion(Competition competition, User user, String solveTime, String compScore) {
       this.competition = competition;
       this.user = user;
       this.solveTime = solveTime;
       this.compScore = compScore;
    }
   
    public Integer getIduserCompetion() {
        return this.iduserCompetion;
    }
    
    public void setIduserCompetion(Integer iduserCompetion) {
        this.iduserCompetion = iduserCompetion;
    }
    public Competition getCompetition() {
        return this.competition;
    }
    
    public void setCompetition(Competition competition) {
        this.competition = competition;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getSolveTime() {
        return this.solveTime;
    }
    
    public void setSolveTime(String solveTime) {
        this.solveTime = solveTime;
    }
    public String getCompScore() {
        return this.compScore;
    }
    
    public void setCompScore(String compScore) {
        this.compScore = compScore;
    }




}


