package pojo;
// Generated Jun 7, 2014 10:51:16 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private String fname;
     private String lname;
     private String username;
     private String dateofbirth;
     private Set userCompetions = new HashSet(0);

    public User() {
    }

    public User(String fname, String lname, String username, String dateofbirth) {
       this.fname = fname;
       this.lname = lname;
       this.username = username;
       this.dateofbirth = dateofbirth;
       this.userCompetions = userCompetions;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getDateofbirth() {
        return this.dateofbirth;
    }
    
    public void setDateofbirth(String dateofbirth) {
        this.dateofbirth = dateofbirth;
    }
    public Set getUserCompetions() {
        return this.userCompetions;
    }
    
    public void setUserCompetions(Set userCompetions) {
        this.userCompetions = userCompetions;
    }




}


